import Head from 'next/head'
import Link from 'next/link'
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>여기까지 어쩐 일로 오셨나요....</div>
      <Link href="/01">
        1번을 보시렵니까...
      </Link>
    </>
  )
}
